import '../../../dist/types/stencil.core';
import { BaseText } from "../../common/base-text";
export declare class WeatherTag implements BaseText {
    el: HTMLStencilElement;
    weatherObject: any;
    originX: string;
    originY: string;
    top: number;
    left: number;
    width: number;
    height: number;
    fill: string;
    fontSize: number;
    angle: number;
    scaleX: number;
    scaleY: number;
    fontWeight: string;
    fontFamily: string;
    textAlign: string;
    fontStyle: string;
    lineHeight: number;
    stroke: string;
    strokeWidth: number;
    strokeLineCap: string;
    strokeLineJoin: string;
    zIndex: number;
    containerHeight: number;
    containerWidth: number;
    temperatureUnit: string;
    temperatureType: string;
    latitude: number;
    longitude: number;
    slideState: number;
    temperature: number;
    weather: any;
    init(attr: any): void;
    checkSlideState(slideState: any): void;
    componentWillLoad(): void;
    componentDidLoad(): void;
    weatherChanged: (event: any) => void;
    componentDidUnload(): void;
    renderTemperature(text: any): JSX.Element;
    renderIcon(): JSX.Element;
    render(): JSX.Element;
}
